version: '3.5'
services:
  milvus:
    image: milvusdb/milvus:v2.2.8
    container_name: milvus-standalone
    ports:
      - "19530:19530"
      - "19121:19121"
    command: ["milvus", "run", "standalone"]
    restart: always
    environment:
      TZ: "UTC"
